### ISSUE TITLE
minimise install instructions

### ISSUE THREAD

**Issue by estebanlm** [sovelten/smallworlds#1]
Hi, 

Nice to see another fan of old stuff (I myself play a lot MUDs) :)

Just want to put that your install instructions are too complicated and can be a lot easier if you do a Baseline instead a Configuration (check here for an example: https://github.com/estebanlm/MUDClient/tree/master/mc/BaselineOfMUDClient.package) 
With that, install smallworlds (as an user, as a developper you still need gitfiletree) will be: 

```
Metacello new 
    repository: 'github://ericvm/smallworlds';
    baseline: 'Smallworlds';
    load.
```

**Comment by sovelten** [comment]
Hi,

Thanks for the reply! I'll see about using Metacello to simplify the
installation process, that's a great tip! But I'm thinking the main
audience, at least for the time being is still the Smalltalk developer.

2016-06-21 10:19 GMT-03:00 Esteban Lorenzano notifications@github.com:

**Comment by sovelten** [comment]
I added a baseline, that's indeed a lot easier!
